# a=int(input("Enter the number"))
# b=[]
# i=0
# while i<a:
#     num=int(input("Enter the number: "))
#     b.append(num)
#     i+=1
# print(b)



# a="deepanjali"
# i=0
# b=[]
# j=5
# while i< len(a):
#     b.append(a[i])
#     b.append(j)
#     i+=1
#     j+=5
# print(b)    
    

# a="deepanjali"
# i=0
# b=[]
# while i<len(a):
#     b.append(a[i])
#     b.append(i*5)
#     i+=1
# print(b)


# a=[1,2,3,4,5,6,7]
# # a=[1,10,2,20,3,10,]
# i=0
# b=[]
# while i<len(a):
#     if a[i]%2==0:
#         b.append(a[i])
#         b.append(20)
#     else:
#         b.append(a[i])
#         b.append(10)    
#     i+=1
# print(b)    


# List=[12,67,98,34]
# i=0
# a=[]
# while i<len(List):
#     # j=0
#     # while j<len(List(i)):
#     #     j+=1
#     i+=1
# print(i)  

# a=[]
# size=int(input("Enter the number:"))
# for i in range(size):
#     num=int(input("Enter thr number: "))
#     a.append(num)
# sum=0
# for i in range(size):
#  sum=sum+a[i]
# print("sum of list elements",sum) 
# # word=["y","s","y"]
# a=1
# b=[]
# while a<=len(word):
#     b.append(word[-a])
#     a+=1
# if b==word:
#     print("palindrome")
# else:
#     print("not")     
# word=input("Enter the name: ")
# a=0
# b=[]
# neew=[]
# while a<len(word):
#     b.append(word[a])
#     a+=1
#     c=0
#     while c<len(b):
#         neew.append(c)
#         c-=1
        
    # print(neew)
# print(b)
# print(neew)
# # if new==b:
#     print("palindrome")
# else:
#     print("not")        


# a=[2,45,65,70,23,54,67,5,25,25,95]
# b=[]
# i=0
# while i<len(a):
#     if a[i]%5==0:
#         b.append(a[i])
#     i+=1
# print(b)    





# size=int(input("Enter the size: "))
# i=0
# a=[]
# sml=0
# lar=0
# max=0
# min=0
# j=0
# for i in range(size):
#     num=int(input("entr the number: "))
#     a.append(num)
#     while i<len(a):
#         if a[i]>max:
#             max=a[i]
#         i+=1
#     # j=0    
#     while j<len(a):
#         if a[j]<min:
#             min=a[j]
#         j+=1
# print(max)
# print(min)                


# a=[[1,2,3],[4,5,3],[6,1,4]]
# i=0
# sum=0
# sum2=0
# sum3=0
# while i<len(a):
#     j=0
#     while j<len(a):
#         sum=sum+a[i][j]
#         sum2=sum+a[i][j]
#         sum3=sum3+a[i][j]
#         j+=1
#     i+=1
# print(sum,sum2,sum3)
# if sum>sum2 and sum>sum3:
#     print(sum,"is greater")
# if sum2>sum and sum2>sum3:
#     print(sum2,"is greater")
# else:
#     print(sum3,"is greater")

# i=0
# count=0
# b=[]
# while 

# from os import remove


a=[1,2,3,4,5,6,7,8,9]
# i=0
# sum=0
# mul=1
# while i <len(a):
#     if a[i]%2==0:
#         sum+=a[i]
#     elif a[i]%2!=0:
#         mul*=a[i]    
#         # print(sum)
#     i+=1  
# print(mul)                                                                                                                                                  ``````````
# print(sum)      




# num=[1,2,3,4]
# i=0
# sum=0
# a=[]
# while i<len(num):
#     sum+=num[i]
#     a.append(sum)
#     i+=1
# print(a)    



# i=0
# while i<=5:
#     if 



# numr=19
# print("Prime numbers:",end=' ')
# for n in range(5,numr):
#     for i in range(2,n):
#         if(n%i==0):
#             break
#     else:
#         print(n,end=' ')        




# a=["apple","chery","mango","banana","qwert","gfds"]
# b=[]
# for i in a:
#         if "a" in i:
#             b.append(i)
# print(b)





# a=int(input("Enter the number:"))
# if a%2==0 or a%3==0 or a%5==0 or a%7==0 or a%9==0:
#     print("It is a not prime number: ")
# else:
    # print("It is primr number: ")    
# 



# i=65
# while i<90:/
    # print(chr(i),end="")
    # print()
    # i+=1
# print(2%3)

# for i in range(1,11):
#     while (i<=100):
#         print(i,"",end=" ")
#         i+=1



# j=1
# while j<=10:
#     i=1
#     while i<=100:
#         print(i,"",end="")
#         i+=1
#     j+=10
#     print()    
    # print(j)
    # if j%10==0:
    # print(j,end=" ")
    
    # j+=10
# i+=1
# print()
# i=1


a=[]
i=0
while i<=100:
    if i%2==0 or i%3==0 or i%5==0 or i%7==0 or i%9==0:
        print()
    else:
        a.append(i)    
    i+=1
print(a)    
# i+=1    